apiVersion: v1
kind: Pod
metadata:
  name: vault-dummy-1
  namespace: web-1
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: kops.k8s.io/instancegroup
            operator: In
            values:
            - seolp
        weight: 1
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kops.k8s.io/instancegroup
            operator: In
            values:
            - seolp
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: nexus-php-seo
  containers:
  - name: vault-dummy-1
    image: geronimomark/vault-dummy:1.3
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    volumeMounts:
    - name: token
      mountPath: "/etc/vault"
      readOnly: true
  volumes:
    - name: token
      secret:
        secretName: vault-secret
  restartPolicy: OnFailure
